# Settings
baseurl: /MA2-ace
permalink: /:categories/:title

# About
title: MA2 ACE
tagline: Alg√®bre Commutative et Effective
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu/'
  - name: Nicolas Perrin
    url: 'http://lmv.math.cnrs.fr/annuaire/nicolas-perrin/'
created: 2014
license:
  name: Creative Commons 4.0 Attribution-ShareAlike
  shortname: CC-BY-SA 4.0
  url: http://creativecommons.org/licenses/by-sa/4.0/
  badge: http://i.creativecommons.org/l/by-sa/4.0/80x15.png

# Display a log in the top bar
#logo: assets/logo/eLeMentS.svg

# Display a GitHub fork me logo in the lower right corner
forkme: yes

# Default configuration for pages.
# Can be used to activate addons on all pages.
defaults:
  - scope:
      path: ''
    values:
      layout: default
      addons:
        favicon: yes
        print-link: yes
        about: yes

create:
  pages: yes


# Collections
collections:
  # Leave that addons collection like this
  # if you want to use addons
  addons:
    output: true
    permalink: /:collection/:path:output_ext
  poly:
    output: false
  polytd:
    output: false
  
kramdown:
  parse_block_html: true

# SASS configuration.
# Better not touch this
sass:
  sass_dir: assets/css
  style: compressed
